---
all:
  hosts:
  vars:
    ansible_user: admin
  children:
    media:
      hosts:
        # ip addresses or dns names of MEDIA hosts
      vars:
        iso_url: "{{ media_iso_url }}"
    main:
      hosts:
        # ip addresses or dns names of MAIN hosts
      vars:
        iso_url: "{{ main_iso_url }}"
