---
all:
  hosts:
  vars:
    ansible_user: admin
  children:
    media:
      hosts:
        10.16.16.133
      vars:
        iso_url: "{{ media_iso_url }}"
    main:
      hosts:
        10.16.16.131 \
        10.16.16.132
      vars:
        iso_url: "{{ main_iso_url }}"
